plugins { id 'com.android.application' }
android {
    namespace 'com.yunari.play'
    compileSdk 35
    defaultConfig {
        applicationId 'com.yunari.play'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.4.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
}
